// List of References - APA 7th, alphabetical. Every entry corresponds to an in-text citation in
// Sections 1–5 or Appendix D. Sources: the verified literature map, the Year 1 LR bibliography,
// and records from the executed Scopus log (17 Aug 2026). Entries carrying a bracketed
// [verify …] note need completion from database exports in the W4 APA pass; DOIs are added then.
module.exports = [
  'Alliger, G. M., & Janak, E. A. (1989). Kirkpatrick’s levels of training criteria: Thirty years later. Personnel Psychology, 42(2), 331–342.',
  'Arthur, W., Jr., Bennett, W., Jr., Edens, P. S., & Bell, S. T. (2003). Effectiveness of training in organizations: A meta-analysis of design and evaluation features. Journal of Applied Psychology, 88(2), 234–245.',
  'Bai, S., Hew, K. F., & Huang, B. (2020). Does gamification improve student learning outcome? Evidence from a meta-analysis and synthesis of qualitative data in educational contexts. Educational Research Review, 30, 100322.',
  'Braun, V., & Clarke, V. (2006). Using thematic analysis in psychology. Qualitative Research in Psychology, 3(2), 77–101.',
  'Braun, V., & Clarke, V. (2019). Reflecting on reflexive thematic analysis. Qualitative Research in Sport, Exercise and Health, 11(4), 589–597.',
  'Braun, V., & Clarke, V. (2022). Thematic analysis: A practical guide. SAGE.',
  'Braun, V., & Clarke, V. (2024). Supporting best practice in reflexive thematic analysis reporting in Palliative Medicine: A review of published research and introduction to the Reflexive Thematic Analysis Reporting Guidelines (RTARG). Palliative Medicine, 38(6), 608–616.',
  'Brown, A. L. (1992). Design experiments: Theoretical and methodological challenges in creating complex interventions in classroom settings. Journal of the Learning Sciences, 2(2), 141–178.',
  'Căpățînă, A., Juárez-Varón, D., Micu, A., & Micu, A. E. (2024). [verify exact title from export]. Journal of Innovation & Knowledge, 9(3), 100530.',
  'Celik, I. (2023). Towards Intelligent-TPACK: An empirical study on teachers’ professional knowledge to ethically integrate artificial intelligence (AI)-based tools into education. Computers in Human Behavior, 138, 107468.',
  'Chai, D. S., Kim, H. S., Kim, K. N., Ha, Y., Shin, S. S. H., & Yoon, S. W. (2025). Generative artificial intelligence in instructional system design. Advances in Developing Human Resources.',
  'Clark, R. C., & Mayer, R. E. (2023). E-learning and the science of instruction: Proven guidelines for consumers and designers of multimedia learning (5th ed.). Wiley.',
  'Cromley, J., Du, Y., & Bhatt, [verify initials] (2025). [verify exact title from export]. Educational Psychology Review.',
  'D’Acunto, F., & Rossi, A. G. (2020). Robo-advisory [Working paper].',
  'D’Ignazio, A., [verify co-authors from export] (2026). Tackling the gender gap in financial literacy: Evidence from a financial education program in the workplace. Education Economics. Advance online publication.',
  'Davis, F. D. (1989). Perceived usefulness, perceived ease of use, and user acceptance of information technology. MIS Quarterly, 13(3), 319–340.',
  'Design-Based Research Collective. (2003). Design-based research: An emerging paradigm for educational inquiry. Educational Researcher, 32(1), 5–8.',
  'Deterding, S., Dixon, D., Khaled, R., & Nacke, L. (2011). From game design elements to gamefulness: Defining “gamification.” In Proceedings of the 15th International Academic MindTrek Conference (pp. 9–15). ACM.',
  'Drobetz, W., Hollstein, F., Otto, T., & Prokopczuk, M. (2024). Estimating stock market betas via machine learning. Journal of Financial and Quantitative Analysis.',
  'Frankel, R., Jennings, J., & Lee, J. (2022). Disclosure sentiment: Machine learning vs. dictionary methods. Management Science, 68(7), 5514–5532.',
  'Fuster, A., Goldsmith-Pinkham, P., Ramadorai, T., & Walther, A. (2022). Predictably unequal? The effects of machine learning on credit markets. Journal of Finance, 77(1), 5–47.',
  'Gagné, R. M. (1985). The conditions of learning and theory of instruction (4th ed.). Holt, Rinehart and Winston.',
  'Gale, N. K., Heath, G., Cameron, E., Rashid, S., & Redwood, S. (2013). Using the framework method for the analysis of qualitative data in multi-disciplinary health research. BMC Medical Research Methodology, 13, 117.',
  'Gu, S., Kelly, B., & Xiu, D. (2020). Empirical asset pricing via machine learning. Review of Financial Studies, 33(5), 2223–2273.',
  'Guest, G., Bunce, A., & Johnson, L. (2006). How many interviews are enough? An experiment with data saturation and variability. Field Methods, 18(1), 59–82.',
  'Holton, E. F., III. (1996). The flawed four-level evaluation model. Human Resource Development Quarterly, 7(1), 5–21.',
  'Hunicke, R., LeBlanc, M., & Zubek, R. (2004). MDA: A formal approach to game design and game research. In Proceedings of the AAAI Workshop on Challenges in Game AI. AAAI Press.',
  'Kaiser, T., Lusardi, A., Menkhoff, L., & Urban, C. (2022). Financial education affects financial knowledge and downstream behaviors. Journal of Financial Economics, 145(2), 255–272.',
  'Kapp, K. M. (2012). The gamification of learning and instruction: Game-based methods and strategies for training and education. Pfeiffer.',
  'Kelly, B., Malamud, S., & Zhou, K. (2024). The virtue of complexity in return prediction. Journal of Finance, 79(1), 459–503.',
  'Kingdom of Saudi Arabia. (2023). Personal Data Protection Law and Implementing Regulations. Saudi Data and Artificial Intelligence Authority.',
  'Kirkpatrick, J. D., & Kirkpatrick, W. K. (2016). Kirkpatrick’s four levels of training evaluation. ATD Press.',
  'Knowles, M. S., Holton, E. F., III, Robinson, P. A., & Caraccioli, [verify initials] (2025). The adult learner: The definitive classic in adult education and human resource development (10th ed.). Routledge.',
  'Kulkarni, P., [verify co-authors from export] (2022). An empirical study on the impact of learning theory on gamification-based training programs. Organization Management Journal, 19(5), 170–188.',
  'Kumar, S., Gunn, A., Rose, R., Pollard, R., Johnson, M., & Ritzhaupt, A. D. (2024). [verify exact title from export]. Online Learning, 28(3), 207–231.',
  'Leiker, D., Finnigan, S., Gyllen, A. R., & Cukurova, M. (2023). Prototyping the use of large language models (LLMs) for adult learning content creation at scale (arXiv:2306.01815). arXiv.',
  'Lincoln, Y. S., & Guba, E. G. (1985). Naturalistic inquiry. SAGE.',
  'Lusardi, A., & Mitchell, O. S. (2014). The economic importance of financial literacy: Theory and evidence. Journal of Economic Literature, 52(1), 5–44.',
  'Mayer, R. E. (2021). Multimedia learning (3rd ed.). Cambridge University Press.',
  'McKenney, S., & Reeves, T. C. (2019). Conducting educational design research (2nd ed.). Routledge.',
  'McKenney, S., & Reeves, T. C. (2021). Educational design research: Portraying, conducting, and enhancing productive scholarship. Medical Education, 55(1), 82–92.',
  'Merrill, M. D. (2002). First principles of instruction. Educational Technology Research and Development, 50(3), 43–59.',
  'Miao, F., & Holmes, W. (2023). Guidance for generative AI in education and research. UNESCO.',
  'Muljana, P. S., [verify co-authors from export] (2024). [verify exact title from export]. Educational Technology Research and Development, 72, 2413–2437.',
  'Noetel, M., Griffith, S., Delaney, O., [verify remaining authors from export] (2022). Multimedia design for learning: An overview of reviews with meta-meta-analysis. Review of Educational Research, 92(3), 413–454.',
  'O’Brien, B. C., Harris, I. B., Beckman, T. J., Reed, D. A., & Cook, D. A. (2014). Standards for reporting qualitative research: A synthesis of recommendations. Academic Medicine, 89(9), 1245–1251.',
  'OECD. (2016). G20/OECD INFE core competencies framework on financial literacy for adults. OECD Publishing.',
  'OECD. (2019). Recommendation of the Council on Artificial Intelligence (OECD AI Principles). OECD Legal Instruments.',
  'OECD. (2022a). Financial competence framework for adults in the European Union. OECD Publishing.',
  'OECD. (2022b). OECD/INFE toolkit for measuring financial literacy and financial inclusion 2022. OECD Publishing.',
  'OECD. (2023). OECD/INFE 2023 international survey of adult financial literacy. OECD Publishing.',
  'Phillips, J. J., & Phillips, P. P. (2016). Handbook of training evaluation and measurement methods (4th ed.). Routledge.',
  'Ponce, H. R., Mayer, R. E., & Torres, [verify initials] (2024). [verify exact title from export]. International Journal of Human–Computer Interaction, 40(11), 2954–2967.',
  'Reio, T. G., Jr., Rocco, T. S., Smith, D. H., & Chang, E. (2017). A critique of Kirkpatrick’s evaluation model. New Horizons in Adult Education and Human Resource Development, 29(2), 35–53.',
  'Rodrigues, L. F., Oliveira, A., & Costa, C. J. (2016). [verify exact title from export]. Computers in Human Behavior, 62, 620–634.',
  'Rossi, A. G., & Utkus, S. P. (2024). The diversification and welfare effects of robo-advising. Journal of Financial Economics, 157, 103869.',
  'Ryan, R. M., & Deci, E. L. (2000). Self-determination theory and the facilitation of intrinsic motivation, social development, and well-being. American Psychologist, 55(1), 68–78.',
  'Ryan, R. M., & Deci, E. L. (2017). Self-determination theory: Basic psychological needs in motivation, development, and wellness. Guilford Press.',
  'Sailer, M., Hense, J. U., Mayr, S. K., & Mandl, H. (2017). How gamification motivates: An experimental study of the effects of specific game design elements on psychological need satisfaction. Computers in Human Behavior, 69, 371–380.',
  'Sailer, M., & Homner, L. (2020). The gamification of learning: A meta-analysis. Educational Psychology Review, 32(1), 77–112.',
  'Saunders, B., Sim, J., Kingstone, T., Baker, S., Waterfield, J., Bartlam, B., Burroughs, H., & Jinks, C. (2018). Saturation in qualitative research: Exploring its conceptualization and operationalization. Quality & Quantity, 52, 1893–1907.',
  'Silva, R., Rodrigues, R., & Leal, C. (2021). Games based learning in accounting education – which dimensions are the most relevant? Accounting Education, 30(2), 159–187.',
  'Sitzmann, T., Kraiger, K., Stewart, D., & Wisher, R. (2006). The comparative effectiveness of web-based and classroom instruction: A meta-analysis. Personnel Psychology, 59(3), 623–664.',
  'Soobhany, A. R., [verify co-authors from export] (2026). Finance Masters: Game-based financial learning for SME managers. Lecture Notes of the Institute for Computer Sciences, Social Informatics and Telecommunications Engineering, 695, 367–384.',
  'Strzelecki, A. (2024). Students’ acceptance of ChatGPT in higher education: An extended unified theory of acceptance and use of technology. Innovative Higher Education, 49, 223–245.',
  'Stufflebeam, D. L., & Zhang, G. (2017). The CIPP evaluation model: How to evaluate for improvement and accountability. Guilford Press.',
  'Tracy, S. J. (2010). Qualitative quality: Eight “big-tent” criteria for excellent qualitative research. Qualitative Inquiry, 16(10), 837–851.',
  'United Arab Emirates. (2021). Federal Decree-Law No. 45 of 2021 on the protection of personal data.',
  'Venkatesh, V. (2022). Adoption and use of AI tools: A research agenda grounded in UTAUT. Annals of Operations Research, 308(1), 641–652.',
  'Venkatesh, V., Morris, M. G., Davis, G. B., & Davis, F. D. (2003). User acceptance of information technology: Toward a unified view. MIS Quarterly, 27(3), 425–478.',
  'Venkatesh, V., Thong, J. Y. L., & Xu, X. (2012). Consumer acceptance and use of information technology: Extending the unified theory of acceptance and use of technology. MIS Quarterly, 36(1), 157–178.',
  'Wang, F., & Hannafin, M. J. (2005). Design-based research and technology-enhanced learning environments. Educational Technology Research and Development, 53(4), 5–23.',
  'Xing, K. (2023). Design and implementation of digital training evaluation management system based on AI’s generative AI technology. In ACM International Conference Proceeding Series (pp. 1222–1226). ACM.',
  'Yan, L., Sha, L., Zhao, L., [verify remaining authors from export] (2024). Practical and ethical challenges of large language models in education: A systematic scoping review. British Journal of Educational Technology, 55(1), 90–112.',
  'Zawacki-Richter, O., Marín, V. I., Bond, M., & Gouverneur, F. (2019). Systematic review of research on artificial intelligence applications in higher education – where are the educators? International Journal of Educational Technology in Higher Education, 16, 39.',
  'Zeng, [verify authors from export] (2024). [verify exact title from export]. British Journal of Educational Technology, 55(5), 1919–1943.',
];
